version: "3"
services:
  db:
    image: mysql:latest
    container_name: parkapi_db
    environment:
      MYSQL_USER: parkapi
      MYSQL_PASSWORD: parkapi
      MYSQL_DATABASE: parkapi
      MYSQL_ROOT_PASSWORD: parkapi
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
